namespace Moss.NET.Sdk;

internal enum ColorKey
{
    BACKGROUND,
    SELECTED,
    LINE_GRAY,
    LINE_GRAY_LIGHT,
    DOCUMENT_GRAY,
    DOCUMENT_BACKGROUND,
    BUTTON_ACTIVE_COLOR,
    BUTTON_ACTIVE_COLOR_INVERTED,
    BUTTON_DISABLED_COLOR,
    BUTTON_DISABLED_LIGHT_COLOR,
    OUTLINE_COLOR,
}